const tweets = [
  
  
  "ಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕು ಸಂವಿಧಾನ ಹಕ್ಕು #StopSilencingBengaluru #ProtestWithFreedom",
  "Let Freedom Park not be a jail for dissent! 🗽 #StopSilencingBengaluru #ProtestWithFreedom",
  "ಪ್ರತಿರೋಧ ಜನರ ಮಧ್ಯ ಇರಬೇಕೆ ಹೊರತು ಪ್ರೀಡಂ ಪಾರ್ಕ ಹಳೇ ಜೈಲ ಅಲ್ಲ. #StopSilencingBengaluru #ProtestWithFreedom",
  "Uphold the right to protest in Bengaluru! ✊ #StopSilencingBengaluru #ProtestWithFreedom",
  "ಪ್ರತಿಭಟಿಸುವುದು ಸ್ವಾತಂತ್ರ್ಯಕ್ಕೆ. #StopSilencingBengaluru #ProtestWithFreedom",
  "March for your rights from Gandhi Statue to Babasaheb Dr. Ambedkar Statue on Oct 2, 2023, at 11 AM. 🚶‍♂️🚶‍♀️ #StopSilencingBengaluru #ProtestWithFreedom", 
  "ಪ್ರತಿಭಟಿಸುವುದು ಸಮಾನತೆ.#StopSilencingBengaluru #ProtestWithFreedom", 
  "We must first make good the right of free speech and free association before we can make any further progress towards our goal... - Mahatma Gandhi #StopSilencingBengaluru #ProtestWithFreedom ",
  "ಬನ್ನಿ ಪ್ರತಿಭಟಿಸು ಹಕ್ಕನ್ನು ಚಲಾಯಿಸೋಣ.#StopSilencingBengaluru #ProtestWithFreedom",
  "We must stand together to defend our right to protest! 🙌 #StopSilencingBengaluru #ProtestWithFreedom", 
  "ಗಾಂಧಿ ಜಯಂತಿಯಂದು ಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕನ್ನು ಕೇಳಲು. #StopSilencingBengaluru #ProtestWithFreedom",
  "The right to protest is fundamental, guaranteed by our Constitution and Dr. Ambedkar. 📜 #StopSilencingBengaluru #ProtestWithFreedom",
  "Previous decisions have stifled this right to protest in Bengaluru. #StopSilencingBengaluru #ProtestWithFreedom", 
  "Bengaluru's right to protest was hollowed out by the 2021 Order. This must be reversed. #StopSilencingBengaluru #ProtestWithFreedom",
  "ದಾರ್ಮಿಕ ಅಲ್ಪಸಂಖ್ಯಾತರಿಗೆ ಅನ್ಯಾಯವಾದಾಗ ಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕನ್ನು ಕೇಳಲು #StopSilencingBengaluru #ProtestWithFreedom",
  "For over a year and a half, the right to protest has been restricted in Bengaluru. #StopSilencingBengaluru #ProtestWithFreedom",
  "ಶೋಷಿತರಿಗೆ ಅನ್ಯಾಯವಾದಾಗ ಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕನ್ನು ಕೇಳಲು #StopSilencingBengaluru #ProtestWithFreedom",
  "Protests are now permitted only in Freedom Park. Let Freedom Park not be a jail for dissent! #StopSilencingBengaluru #ProtestWithFreedom",
  "ಬೆಂಗಳೂರು ಪೊಲೀಸ್ ಆಯುಕ್ತರೆ ಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕು ಸಂವಿಧಾನದ ಹಕ್ಕು #StopSilencingBengaluru #ProtestWithFreedom",
  "Farmers, Dalit activists, Powrakarmikas, LGBTQI community members, and more have been denied their right to protest. #StopSilencingBengaluru #ProtestWithFreedom",
  "In Bengaluru, cases are filed against those exercising their fundamental right to protest. #StopSilencingBengaluru #ProtestWithFreedom", 
  "ದ್ವೇಷ ಬಿತ್ತುವ ಸಂದರ್ಭದಲ್ಲಿ ಪ್ರೀತಿಯಿಂದ ಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕನ್ನು ಕೇಳಲು #StopSilencingBengaluru #ProtestWithFreedom",
  "Join us in upholding the right to protest! ✊ #StopSilencingBengaluru #ProtestWithFreedom",
  "ದೌರ್ಜನ್ಯ ನಡೆಸುವ ಸಂದರ್ಭದಲ್ಲಿ ಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕನ್ನು ಕೇಳಲು #StopSilencingBengaluru #ProtestWithFreedom",
  "Withdraw all cases against those who exercised their right to protest, including workers, farmers, Dalits, women, and marginalized communities. ⚖️ #StopSilencingBengaluru #ProtestWithFreedom",
  "ಯುವಜನಕ್ಕೆ ಅನ್ಯಾಯವಾದಾಗ ಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕನ್ನು ಕೇಳಲು #StopSilencingBengaluru #ProtestWithFreedom",
  "Since the govt. has not withdrawn the unconstitutional order against protesting in Bengaluru, on October 2, 2023, we march from Gandhi Statue to Babasaheb Dr. B.R. Ambedkar Statue to assert our democratic right to protest. 🚶‍♂️🚶‍♀️ #StopSilencingBengaluru #ProtestWithFreedom",
  "ಲೈಂಗಿಕ/ಲಿಂಗತ್ವ ಅಲ್ಪಸಂಖ್ಯಾತರಿಗೆಅನ್ಯಾಯವಾದಾಗಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕನ್ನು ಕೇಳಲು. #StopSilencingBengaluru #ProtestWithFreedom",
  "Freedom Park should be a symbol of freedom, not repression! 🌳 #StopSilencingBengaluru #ProtestWithFreedom",
  "ದಲಿತರಿಗೆ ಅನ್ಯಾಯವಾದಾಗಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕನ್ನು ಕೇಳಲು #StopSilencingBengaluru #ProtestWithFreedom",
  "Farmers, workers, and marginalized communities rely on the power of protest for their voices to be heard. 🌾👷‍♂️👷‍♀️ #StopSilencingBengaluru #ProtestWithFreedom",
  "ರೈತರಿಗೆ ಅನ್ಯಾಯವಾದಾಗ ಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕನ್ನು ಕೇಳಲು #StopSilencingBengaluru #ProtestWithFreedom", 
  "Protests are an essential component of freedom of expression. #StopSilencingBengaluru #ProtestWithFreedom",
  "ಮಹಿಳೆಯರಿಗೆ ಅನ್ಯಾಯವಾದಾಗ ಪ್ರತಿಭಟಿಸುವ ಹಕ್ಕನ್ನು ಕೇಳಲು #StopSilencingBengaluru #ProtestWithFreedom",
  "Protests drive change and hold governments accountable. The right to protest is crucial in a healthy democracy. 🏛️ #StopSilencingBengaluru #ProtestWithFreedom",
  "Citizen groups have repeatedly asked the government to withdraw this unconstitutional order against protesting in Bengaluru. #StopSilencingBengaluru #ProtestWithFreedom",
  "Demand the withdrawal of the unconstitutional 2021 Order against protests in Bengaluru! 📜 #StopSilencingBengaluru #ProtestWithFreedom",
  "Stand up for your right to voice dissent! 🗣️ #StopSilencingBengaluru #ProtestWithFreedom", 
  "Bengaluru deserves the right to express its grievances openly. 📢 #StopSilencingBengaluru #ProtestWithFreedom",  
  "Let Bengaluru echo with the voices of those who demand justice! 🔊 #StopSilencingBengaluru #ProtestWithFreedom", 
  "Mahatma Gandhi's words ring true: We must defend elementary rights with our lives. 💪 #StopSilencingBengaluru #ProtestWithFreedom",
  "Upholding the right to protest is an act of defending democracy. 🇮🇳 #StopSilencingBengaluru #ProtestWithFreedom",
  "The 2021 Order curtailing protests in Bengaluru restricts our ability to hold those in power accountable. #StopSilencingBengaluru #ProtestWithFreedom",
  "Stand together for the right to assemble and speak out! 🤝 #StopSilencingBengaluru #ProtestWithFreedom",
  "Democracy thrives when citizens can freely voice their concerns. 🏛️🗳️ #StopSilencingBengaluru #ProtestWithFreedom", 
  "Democracy thrives when citizens can freely voice their concerns. 🏛️🗳️ #StopSilencingBengaluru #ProtestWithFreedom", 
  "The 2021 Order must be repealed for a truly democratic Bengaluru. 📜 #StopSilencingBengaluru #ProtestWithFreedom", 
  "Our democracy is only as strong as our commitment to our rights. 🇮🇳 #StopSilencingBengaluru #ProtestWithFreedom", 
  "The government must revoke the anti-people law barring all protests outside Freedom Park.  #Protestwithfreedom", 
  

    
  
]
